### PR TITLE
Update Project Title to Behavior Cloning

### PR DESCRIPTION
**Pull request by manavkataria**
@domluna, @andrewpaster Kindly review.

### CODE REVIEW

**Comment by dsilver829** [comment]
What is the reason for this suggested change?

We have always called this project "Behavioral Cloning", as "Behavioral" is an adjective that modifies the noun, "Cloning".

If I search for "Behavioral Cloning" on Google, I get ~3000 results, compared to ~900 for "Behavior Cloning".

So I think "Behavioral Cloning" might be the better form.

**Comment by manavkataria** [comment]
Thanks @domluna for accepting the PR. 

@dsilver829 If you look at the actual diff the update on `writeup_template.md` was 'Traffic Sign Recognition' -> 'Behavioural Cloning'; I could have worded the title of the pull-request more clearly to avoid confusion.

**Comment by dsilver829** [comment]
Ha! Don't I feel like an idiot. Good catch ;-)

**Comment by domluna** [comment]
😀

**Pull request merged**
